services:
  sortify:
    image: "ghcr.io/lklynet/sortify:latest"
    environment:
      PORT: 3001
      SUBSONIC_URL: ${SUBSONIC_URL:-}
      SUBSONIC_USER: ${SUBSONIC_USER:-}
      SUBSONIC_PASSWORD: ${SUBSONIC_PASSWORD:-}
      LASTFM_API_KEY: ${LASTFM_API_KEY:-}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-flash-lite-latest}
      MAX_TRACKS_PER_PLAYLIST: ${MAX_TRACKS_PER_PLAYLIST:-20}
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./data:/data
